### ISSUE TITLE
Redefine Data Recvd to make sense for HTTP/2

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-overview#13]
We currently use the term "Data Recvd" and reference QUIC explicitly. That definition does not really make sense for HTTP/2; we should redefine it.

See w3c/webtransport#580

**Comment by DavidSchinazi** [comment]
Chair: discussed at IETF 120, there was a discussion about replacing with Data Recvd with Data Sent
