### ISSUE TITLE
Streams and messages

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-overview#3]
Alan has [pointed out on the mailing list](https://mailarchive.ietf.org/arch/msg/webtransport/rZ4JPXw4MPPw21L3HN_rDXkvsFw/) that we do not provide a reliable in-order message abstraction.  The draft currently discusses this as follows:

> Stream: A stream is a sequence of bytes that is reliably delivered to the receiving application in the same order as it was transmitted by the sender. Streams can be of arbitrary length, and therefore cannot always be buffered entirely in memory. It is expected for transport protocols and APIs to provide partial stream data to the application before the stream has been entirely received.
>
> Message: A message is a stream that is sufficiently small that it can be fully buffered before being passed to the application. WebTransport does not define messages as a primitive, since from the transport perspective they can be simulated by fully buffering a stream before passing it to the application. However, this distinction is important to highlight since some of the similar protocols and APIs (notably WebSocket [RFC6455]) use messages as a core abstraction.

We went with streams of bytes as our fundamental primitive since that was the primitive of QUIC, HTTP/2 and HTTP/3.  WebSocket, SCTP and RTC Data Channels all use streams of messages.  Fundamentally, streams of messages are streams of bytes with some boundaries preserved.  As an application, going between those two is easy:

- Streams of bytes -> streams of messages: this can be done by application adding its own framing, which is not that hard.
- Streams of messages -> streams of bytes: this can be done by simply ignoring the message boundaries.

The question here is whether we want to:

1. Keep situation as-is
1. Replace streams of bytes with streams of messages, to be consistent with WebSocket and DataChannel.
1. Support both

**Comment by kixelated** [comment]
I'm a big fan of the HTTP/3 approach and using individual streams for framing messages, so option 1.

Sending a message means creating a new stream, writing the message, closing the stream. Receiving a message means accepting a stream, buffering all of the contents, and returning the message. Buffering a WHATWG stream into a single ArrayBuffer is a little annoying, but it can be done with a simple helper function.

It seems very possible to port an application using WebSockets to WebTransport by doing the above, although messages could be delivered out of order. If head-of-line blocking is desired, which I hope becomes less common, the application can add it's own framing like you suggested.

**Comment by vasilvv** [comment]
We've not discussed this recently, and I believe there is currently no interest in adding a dedicated message structure to either streams or datagrams.  Closing it as such; please reopen if you have a proposal for a dedicated message API both H/2 and H/3.

**Comment by afrind** [comment]
I think it's fine to close this issue.  I also think there's an opportunity for someone to get out in front of this and create javascript and server-side libraries for message framing over WebTransport streams (could Capsule Protocol be viable?).  I get the sense a lot of WebSocket developers use the built-in reliable message framing and WebTransport leaves this gap unfilled.
