### ISSUE TITLE
Overview draft and HTTP

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-overview#6]
No text in the overview draft currently assumes that WebTransport is running over HTTP, largely because it was written before we made a decision on WT-over-QUIC vs WT-over-HTTP/3.  I wonder if it makes sense to add anything HTTP-specific that's common to H/3 and H/2 draft now that we have that option.  One aspect I was thinking about is registering an upgrade token (right now, H2 draft cites H3 draft for this, but it feels somewhat wrong).

**Comment by DavidSchinazi** [comment]
Chair: discussed during editor's meeting, close with no action - I'll open a separate issue for the IANA registry
